"""Add is learning field in words

Revision ID: 6b336725db3c
Revises: e0eeb83c809a
Create Date: 2026-04-17 16:22:35.477372

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6b336725db3c"
down_revision: Union[str, Sequence[str], None] = "e0eeb83c809a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "words",
        sa.Column("is_learning", sa.Boolean(), nullable=False, server_default="true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("words", "is_learning")
    # ### end Alembic commands ###
