"""changed models word

Revision ID: e0eeb83c809a
Revises: 6163c6a09293
Create Date: 2026-02-20 15:18:55.370665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0eeb83c809a'
down_revision: Union[str, Sequence[str], None] = '6163c6a09293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('orig_word', sa.String(), nullable=True))
    op.add_column('words', sa.Column('translate_word', sa.String(), nullable=True))
    op.add_column('words', sa.Column('description', sa.String(), nullable=True))
    op.drop_index(op.f('ix_words_english_word'), table_name='words')
    op.create_index(op.f('ix_words_orig_word'), 'words', ['orig_word'], unique=False)
    op.drop_column('words', 'english_word')
    op.drop_column('words', 'learned')
    op.drop_column('words', 'russian_word')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('russian_word', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('words', sa.Column('learned', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('words', sa.Column('english_word', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_words_orig_word'), table_name='words')
    op.create_index(op.f('ix_words_english_word'), 'words', ['english_word'], unique=False)
    op.drop_column('words', 'description')
    op.drop_column('words', 'translate_word')
    op.drop_column('words', 'orig_word')
    # ### end Alembic commands ###
